// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: exercises.sql

package database

import (
	"context"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (name, photo_url)
VALUES ($1, $2)
RETURNING id, name, photo_url
`

type CreateExerciseParams struct {
	Name     string
	PhotoUrl string
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, createExercise, arg.Name, arg.PhotoUrl)
	var i Exercise
	err := row.Scan(&i.ID, &i.Name, &i.PhotoUrl)
	return i, err
}

const getExerciseById = `-- name: GetExerciseById :one
SELECT id, name, photo_url FROM exercises
WHERE id = $1
`

func (q *Queries) GetExerciseById(ctx context.Context, id int32) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExerciseById, id)
	var i Exercise
	err := row.Scan(&i.ID, &i.Name, &i.PhotoUrl)
	return i, err
}
