// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"database/sql"
)

type MuscleGroup struct {
	ID       int32
	Name     string
	PhotoUrl string
}

type User struct {
	ID       int32
	Name     string
	Gender   sql.NullString
	Role     string
	Email    string
	Password string
}
