// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"database/sql"
	"time"
)

type Exercise struct {
	ID       int32
	Name     string
	PhotoUrl string
}

type ExercisesMuscleGroup struct {
	ID            int32
	ExerciseID    int32
	MuscleGroupID int32
}

type MuscleGroup struct {
	ID       int32
	Name     string
	PhotoUrl string
}

type Set struct {
	ID         int32
	WorkoutID  int32
	ExerciseID int32
	Reps       int32
	Weight     int32
}

type User struct {
	ID       int32
	Name     string
	Gender   sql.NullString
	Role     string
	Email    string
	Password string
}

type Workout struct {
	ID        int32
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
