// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: muscle_groups.sql

package database

import (
	"context"
)

const createMuscleGroup = `-- name: CreateMuscleGroup :one
INSERT INTO muscle_groups (name, photo_url)
VALUES ($1, $2)
RETURNING id, name, photo_url
`

type CreateMuscleGroupParams struct {
	Name     string
	PhotoUrl string
}

func (q *Queries) CreateMuscleGroup(ctx context.Context, arg CreateMuscleGroupParams) (MuscleGroup, error) {
	row := q.db.QueryRowContext(ctx, createMuscleGroup, arg.Name, arg.PhotoUrl)
	var i MuscleGroup
	err := row.Scan(&i.ID, &i.Name, &i.PhotoUrl)
	return i, err
}
