openapi: 3.0.0
info:
  title: Gym logs API
  version: 1.0.0
servers:
  - url: http://localhost:5000/v1
paths:
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/User'
        '500':
          description: Internal Server Error
  /muscle-groups:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'components.yaml#/components/schemas/MuscleGroup'
        '500':
          description: Internal Server Error
          